Memory swap
spcl/mignificient pull request #1
Opened 2024-04-01 04:01 UTC by EricPyZhou

`ptrSizeStore` is a vector of a structure named `DataElement` that contain device memory pointer, host memory pointer and size.
 
`swap_out`:
allocate host memory, copy everything element in `ptrSizeStore` into host, **free device memory**.

`swap_in`:
allocate device memory in the original location, copy everything from host to device, **free host memory**.

2024-04-01 04:01 UTC, EricPyZhou commented
I will remove `test_swap.cu` and `test_swap` once review is done.

and Error handling is needed in the future to handle, for example, when `swap_in` is called before `swap_out` and there are elements in `ptrSizeStore` that contain nullptr of `hostPtr` because of executing cudaMalloc(): https://github.com/spcl/mignificient/blob/1c2046d5605449cac649ab68e226648cc2fdffa7/gpuless/trace/manager/manager_device.cpp#L85

2024-04-01 12:26 UTC, mcopik requested changes

2024-04-01 12:26 UTC, mcopik commented on gpuless/trace/manager/manager_device.cpp
> +        cudaMemcpy(buffer.hostPtr, buffer.devicePtr, buffer.size, cudaMemcpyDeviceToHost);
Please use here async copy. Default memcpy will synchronize after every copy.

2024-04-01 12:26 UTC, mcopik commented on gpuless/trace/manager/manager_device.cpp
> +        cudaMemcpy(buffer.devicePtr, buffer.hostPtr, buffer.size, cudaMemcpyHostToDevice);
as below - async copies :)

2024-10-10 20:06 UTC, mcopik commented
Thanks! I had to manually apply your changes since gpuless has been moved to a submodule. I used your implementation and extended it with full memory virtualization.

https://github.com/spcl/gpuless/commit/8fc7af0a8f8d3d795190df1a1848355952402475

2024-10-10 20:06 UTC, closed without merging